name: Routine Update

on:
  schedule:
    - cron: "50 4 * * *"
      
jobs:
  bot:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: bash ./run.sh

